# Generated by Django 3.1 on 2021-03-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('designer', 'designer'), ('customer', 'customer')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
