# Generated by Django 3.1 on 2021-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='status_admin',
            field=models.CharField(choices=[('admin', 'admin')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
