# Generated by Django 3.1 on 2021-03-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_myuser_status_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='status_admin',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('designer', 'designer'), ('customer', 'customer')], default='customer', max_length=20),
        ),
    ]
