# Generated by Django 3.1 on 2021-03-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
