# Generated by Django 3.1 on 2021-03-13 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0005_auto_20210313_1525'),
        ('main', '0007_auto_20210313_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='profiledesigner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_designer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilecustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
