# Generated by Django 3.1 on 2021-03-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_auto_20210313_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecustomer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profiledesigner',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
