# Generated by Django 3.1 on 2021-03-18 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='post',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='product',
        ),
    ]
